ignore resources when tree node is collapsed (#132)
redhat-developer/intellij-kubernetes pull request #133
Opened 2020-12-02 17:14 UTC by adietish

fixes #132

2020-12-03 12:43 UTC, adietish commented
in a first test this seems not to work: 
steps:
1. ASSERT: have a custom resource definition:
```
echo "apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: cars.openshift.pub
spec:
  group: openshift.pub
  names:
    kind: Car
    listKind: CarList
    plural: cars
    singular: car
  scope: Cluster
  subresources:
    status: {}
  versions:
  - name: v1alpha1
    served: true
    storage: false
  - name: v1beta1
    served: true
    storage: true
  names:
    kind: Car
    plural: cars" | kubectl apply -f -
```
2. EXEC: unfold "Custom Resources" > "cars"
3. EXEC: collapse "cars"
4. EXEC: repeat 2 & 3 several times and eventually have "cars" unfolded
5. EXEC: create a new car: 
```
$ echo "apiVersion: openshift.pub/v1beta1
kind: Car
metadata:
  name: chevrolet
spec:
  date_of_manufacturing: "2002-07-01T00:00:00Z"
  engine: CH654321" | kubectl apply -f -
```

Result:
There's no child popping up for "Custom Resources" > "cars"

Expected Result:
"Custom Resources" > "cars" should have a child popping up called "chevrolet"

2021-03-18 14:44 UTC, adietish commented
Works for me now. It can take a few sec before the new car appears though, because watching happens in the background, in a thread.

2021-03-18 17:08 UTC, lstocchi requested changes

2021-03-18 17:08 UTC, lstocchi commented on src/main/kotlin/com/redhat/devtools/intellij/kubernetes/model/ResourceModel.kt
> +        contexts.current?.watch(kind)
Should this be stopWatch?

2021-03-18 17:08 UTC, lstocchi commented on src/main/kotlin/com/redhat/devtools/intellij/kubernetes/model/ResourceModel.kt
> +        contexts.current?.watch(definition)
Should this be stopWatch?

2021-03-19 09:06 UTC, adietish commented on src/main/kotlin/com/redhat/devtools/intellij/kubernetes/model/ResourceModel.kt
> +        contexts.current?.watch(kind)
ouch, thanks for pointing out.

2021-03-19 10:50 UTC, adietish commented
@lstocchi verified, usecase works for me. Also further iterations where I collapse, unfold, create, delete etc. Please verify.

2021-03-19 11:35 UTC, lstocchi reviewed
`Stop watching` works fine but i have a doubt (bc i had complains for this in IJ tekton as well). If you remove the watch and something changes on cluster, when you re-expand the node you don't see the actual situation. 
BTW the behavior it is the same as in vscode with this. 

E.g I expand the tree until secrets 
![image](https://user-images.githubusercontent.com/49404737/111773258-3c29ee00-88ae-11eb-8fd5-fc937e484e6a.png)

I create a new secret
```
apiVersion: v1
kind: Secret
metadata:
  name: test-1
type: Opaque
data:
  password: b3Bz
```
The tree is updated fine. Now i collapse the secrets node, then the configuration node.
I delete some secrets, create a new one. 
At this point if i re-expand the secrets node i don't see the real situation.

2021-03-19 13:08 UTC, adietish commented
> `Stop watching` works fine but i have a doubt (bc i had complains for this in IJ tekton as well). If you remove the watch and something changes on cluster, when you re-expand the node you don't see the actual situation.
gotcha, good catch!

I need to figure out why the following happens:

*Steps:*
1. ASSERT: have Configuration > Secrets expanded
2. EXEC: create secret:
```
echo "apiVersion: v1
kind: Secret
metadata:
  name: test-1
type: Opaque
data:
  password: b3Bz" | kubectl apply -f -
```
3. ASSERT: secret "test-1" appears
4. EXEC: collapse Secret, Configuration
5. EXEC: delete secret "test-1", create secret "test-2"
6. EXEC: expand Configuration > Secret

*Result:*
Secrets "test-1", "test-2" are listed

*Expected Result:**
Only secret "test-2" is listed.

2021-03-19 13:39 UTC, adietish commented
The reason for this is that the resource was deleted when the watch wasn't watchig (was stopped). When the "Secrets" node is expanded, the cache still contains the secret that was killed. It looks as if fixing this is simple: clear the cache when stopping the watch.

2021-03-19 14:21 UTC, adietish commented
@lstocchi fixed via clearing the cache when stopping the watch. Please re-review.

2021-03-19 14:28 UTC, lstocchi approved these changes
Awesome, works perfectly!! GJ!!

2021-03-19 14:28 UTC, merged