release 0.6.0 (#451)
redhat-developer/intellij-kubernetes pull request #452
Opened 2022-07-12 17:11 UTC by adietish

fixes #451

2022-07-12 18:19 UTC, lstocchi approved these changes
LGTM, worth mentioning the follow logs action in the README?

2022-07-12 19:37 UTC, adietish commented
> LGTM, worth mentioning the follow logs action in the README?

Excellent point, will add a section to the README

2022-07-13 06:36 UTC, jeffmaury approved these changes
LGTM

2022-07-13 10:26 UTC, adietish commented
added entries to the README, waiting for @mohitsuman to review my english

2022-07-13 11:49 UTC, mohitsuman requested changes

2022-07-13 11:49 UTC, mohitsuman commented on README.md
> + - Follow logs from your clusters
```suggestion
 - Follow logs from the connected cluster resource
```

2022-07-13 11:49 UTC, mohitsuman commented on README.md
> +A dedicated tab continuously displays the messages that the chosen resource sends to its log.
```suggestion
There is a dedicated tab to display the log messages for the selected Kubernetes resource.
```

2022-07-13 11:54 UTC, adietish commented
@mohitsuman thx for the improvements!

2022-07-13 11:56 UTC, jeffmaury commented on README.md
> +Intellij-Kubernetes allows you to follow the logs of Pods, Jobs and Builds.
extension is for VSCode, plugin is to be used here

2022-07-13 12:38 UTC, merged