bump kubernetes-client to 6.2.0
redhat-developer/intellij-kubernetes pull request #548
Opened 2022-12-07 15:12 UTC by adietish

fixes #500

2022-12-19 13:43 UTC, adietish commented
For this bump to work the kubernetes-client needs to include the following PR: https://github.com/fabric8io/kubernetes-client/pull/4689

2023-01-03 09:09 UTC, adietish commented on gradle.properties
> +kubernetesClientVersion=6.4-SNAPSHOT
should be changed to 6.4.0 once it's released

2023-01-18 02:21 UTC, cloorc commented
Will this update support `describe` command? It seems like the old `kubernetes-client` release doesn't support it yet.

2023-01-20 15:18 UTC, adietish commented
Hi @cloorc 

thanks for chiming in, we love to get user feedback and try to match peoples need if possible.

> Will this update support `describe deployment/statefulset/...` command?
What kind of support would you like this plugin to provide? In the editor?

2023-01-20 15:35 UTC, adietish commented
@jeffmaury, @lstocchi: please review. All other plugins depend on this to bump themselves too.

2023-01-22 05:15 UTC, cloorc commented
> Hi @cloorc
> 
> thanks for chiming in, we love to get user feedback and try to match users needs if possible.
> 
> > Will this update support `describe deployment/statefulset/...` command?
> 
> What kind of support would you like this plugin to provide? A context menu item to the tree which opens a dedicated output like the jetbrains plugin?

Hmm, I'm developing some features like `describe deployment xxx` that have been implemented in `vscode` `kubernetes` plugin. And I ware an old `vscode` user that would use `kubernetes` plugin frequently. Now I back to `IntellijIDEA` for `java development user experience`. However, features supported by `kubernetes` are not as rich as `vscode` yet.

Just something interesting to talk about. I'm going to use native command line tools to support some kubernetes features that `kubernetes-client` hasn't provided yet.

Thanks a lot!

2023-01-23 09:28 UTC, adietish commented
> > Hi @cloorc
> > thanks for chiming in, we love to get user feedback and try to match users needs if possible.
> > > Will this update support `describe deployment/statefulset/...` command?
> > 
> > 
> However, features supported by `kubernetes` are not as rich as `vscode` yet.

indeed, we're getting there but it takes time :)

> 
> Just something interesting to talk about. I'm going to use native command line tools to support some kubernetes features that `kubernetes-client` hasn't provided yet.

excellent idea, I also thought that this would be very handy when trying to inspect a k8s resource. 
I filed #553 and glad if you can add your thoughts in the comments. Of course any contribution is more than welcome. With or without your help, I can plan to start this in the next iteration.

> 
> Thanks a lot!

very welcome, glad if we can provide something that's useful to you and we're very thankful to get your feedback.

2023-01-23 09:30 UTC, adietish commented
@jeffmaury, @lstocchi: could you please test this? It is required for all the other bumps in the various plugins that depend on this plugin.

2023-01-23 14:29 UTC, lstocchi requested changes
I see two errors if i start switching namespace but i am not sure how to replicate it as, sometimes, i have two errors, other times only one, or nothing at all...

1. having a cluster with atleast two namespaces
2. the default one does not have any pod
3. the other (`tekton-pipelines` in my case) have two pods
4. i'm in the `tekton-pipelines` -> expand minikube node -> expand pods
5. switch ns to default  
6. sometimes i face the error, if not i expand the pods node and i switch ns

In the gif below the tree broke up, in other cases it keeps working
![break-k8s](https://user-images.githubusercontent.com/49404737/214064127-06964d6e-24ec-4cbd-8953-a48ed7f02e1d.gif)


The errors i get are two
the first

```
com.redhat.devtools.intellij.kubernetes.actions.UseNamespaceAction 
2023-01-23 15:19:03,640 [  58397]  ERROR - rains.concurrency.AsyncPromise - {
                elemen…ontext.name
            } must not be null 
java.lang.NullPointerException: {
                elemen…ontext.name
            } must not be null
	at com.redhat.devtools.intellij.kubernetes.tree.TreeStructure$ContextDescriptor.getLabel(TreeStructure.kt:170)
	at com.redhat.devtools.intellij.kubernetes.tree.TreeStructure$ContextDescriptor.getLabel(TreeStructure.kt:155)
	at com.redhat.devtools.intellij.kubernetes.tree.TreeStructure$Descriptor.update(TreeStructure.kt:306)
	at com.intellij.ide.util.treeView.PresentableNodeDescriptor.getUpdatedPresentation(PresentableNodeDescriptor.java:76)
	at com.intellij.ide.util.treeView.PresentableNodeDescriptor.update(PresentableNodeDescriptor.java:29)
	at com.intellij.ui.tree.StructureTreeModel$Node.update(StructureTreeModel.java:454)
	at com.intellij.ui.tree.StructureTreeModel$Node.<init>(StructureTreeModel.java:435)
	at com.intellij.ui.tree.StructureTreeModel$Node.<init>(StructureTreeModel.java:428)
	at com.intellij.ui.tree.StructureTreeModel.getValidChildren(StructureTreeModel.java:389)
	at com.intellij.ui.tree.StructureTreeModel.validateChildren(StructureTreeModel.java:298)
	at com.intellij.ui.tree.StructureTreeModel.getNode(StructureTreeModel.java:292)
	at com.intellij.ui.tree.StructureTreeModel.getChildren(StructureTreeModel.java:312)
	at com.intellij.ui.tree.AsyncTreeModel$CmdGetChildren.getNode(AsyncTreeModel.java:545)
	at com.intellij.ui.tree.AsyncTreeModel$Command.get(AsyncTreeModel.java:440)
	at com.intellij.ui.tree.AsyncTreeModel$Command.get(AsyncTreeModel.java:406)
	at com.intellij.util.concurrency.Invoker$Task.run(Invoker.java:316)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:178)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:688)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:634)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:64)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:165)
	at com.intellij.util.concurrency.Invoker.invokeSafely(Invoker.java:203)
	at com.intellij.util.concurrency.Invoker.lambda$offerSafely$0(Invoker.java:183)
	at com.intellij.util.concurrency.Invoker$Background.lambda$offer$0(Invoker.java:541)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:216)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:27)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.execute(BoundedTaskExecutor.java:195)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:213)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:184)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

the second
```
io.fabric8.kubernetes.client.KubernetesClientException: Failed to parse the kubeconfig.
	at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:129)
	at io.fabric8.kubernetes.client.Config.loadFromKubeconfig(Config.java:748)
	at io.fabric8.kubernetes.client.Config.tryKubeConfig(Config.java:647)
	at io.fabric8.kubernetes.client.Config.autoConfigure(Config.java:291)
	at io.fabric8.kubernetes.client.Config.autoConfigure(Config.java:287)
	at com.redhat.devtools.intellij.kubernetes.model.client.ClientAdapter$Factory.create(ClientAdapter.kt:52)
	at com.redhat.devtools.intellij.kubernetes.model.AllContexts$2.invoke(AllContexts.kt:79)
	at com.redhat.devtools.intellij.kubernetes.model.AllContexts$2.invoke(AllContexts.kt:79)
	at com.redhat.devtools.intellij.kubernetes.model.AllContexts$client$1.invoke(AllContexts.kt:87)
	at com.redhat.devtools.intellij.kubernetes.model.AllContexts$client$1.invoke(AllContexts.kt:86)
	at com.redhat.devtools.intellij.kubernetes.model.util.ResettableLazyProperty.get(ResettableLazyProperty.kt:30)
	at com.redhat.devtools.intellij.kubernetes.model.AllContexts.getAll(AllContexts.kt:101)
	at com.redhat.devtools.intellij.kubernetes.model.AllContexts.getCurrent(AllContexts.kt:93)
	at com.redhat.devtools.intellij.kubernetes.model.ResourceModel.getCurrentContext(ResourceModel.kt:90)
	at com.redhat.devtools.intellij.kubernetes.tree.OpenShiftStructure.canContribute(OpenShiftStructure.kt:142)
	at com.redhat.devtools.intellij.kubernetes.tree.TreeStructure.getValidContributions(TreeStructure.kt:119)
	at com.redhat.devtools.intellij.kubernetes.tree.TreeStructure.createDescriptor(TreeStructure.kt:103)
	at com.intellij.ui.tree.StructureTreeModel$Node.<init>(StructureTreeModel.java:428)
	at com.intellij.ui.tree.StructureTreeModel.getValidRoot(StructureTreeModel.java:366)
	at com.intellij.ui.tree.StructureTreeModel.getRoot(StructureTreeModel.java:281)
	at com.intellij.ui.tree.StructureTreeModel.getRoot(StructureTreeModel.java:33)
	at com.intellij.ui.tree.AsyncTreeModel$CmdGetRoot.getNode(AsyncTreeModel.java:469)
	at com.intellij.ui.tree.AsyncTreeModel$Command.get(AsyncTreeModel.java:440)
	at com.intellij.ui.tree.AsyncTreeModel$Command.get(AsyncTreeModel.java:406)
	at com.intellij.util.concurrency.Invoker$Task.run(Invoker.java:316)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:178)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:688)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:634)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:64)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:165)
	at com.intellij.util.concurrency.Invoker.invokeSafely(Invoker.java:203)
	at com.intellij.util.concurrency.Invoker.promise(Invoker.java:250)
	at com.intellij.util.concurrency.Invoker.compute(Invoker.java:82)
	at com.intellij.ui.tree.AsyncTreeModel.submit(AsyncTreeModel.java:269)
	at com.intellij.ui.tree.AsyncTreeModel$1.process(AsyncTreeModel.java:48)
	at com.intellij.util.ui.tree.TreeModelAdapter.treeStructureChanged(TreeModelAdapter.java:41)
	at com.intellij.util.ui.tree.TreeModelListenerList.treeStructureChanged(TreeModelListenerList.java:61)
	at com.intellij.util.ui.tree.AbstractTreeModel.treeStructureChanged(AbstractTreeModel.java:31)
	at com.intellij.ui.tree.StructureTreeModel.invalidateInternal(StructureTreeModel.java:211)
	at com.intellij.ui.tree.S [...]

2023-01-24 15:04 UTC, lstocchi approved these changes
Tried again with an ocp cluster. Everything works fine, probably my env is broken

2023-01-24 15:36 UTC, adietish commented
@lstocchi thanks!
asked @olkornii to test ITs against this since this requires publishing to marketplace (so that all our plugins that depend on this plugin can reference it)

2023-01-26 10:46 UTC, adietish commented
@olkornii ran IT tests and found a few minor bugs in the editor (ex. when editing a cluster resource you get a pull notification right when the editor is opened). We'll not tackle those since the editor is overhauled for the support of multiple resources.

2023-01-26 10:47 UTC, merged