release 0.8.1 (#589)
redhat-developer/intellij-kubernetes pull request #590
Opened 2023-04-03 13:21 UTC by adietish

fixes #589

2023-04-03 15:45 UTC, sbouchet requested changes

2023-04-03 15:45 UTC, sbouchet commented on src/main/resources/META-INF/plugin.xml
>          <h3>0.8.0</h3>
```suggestion
        <h3>0.8.1</h3>
```

2023-04-04 08:43 UTC, sbouchet approved these changes
/lgtm

2023-04-04 09:18 UTC, merged

2023-04-04 09:30 UTC, adietish commented
published to marketplace, waiting for approval
<img width="1257" alt="image" src="https://user-images.githubusercontent.com/25126/229749887-1ef24c43-4db8-421a-9112-65c92957b24d.png">